
project: l-js-monolith

# Set this if you want to carry over parent process' environment variables
# carry_env: true 


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development


#
# Providers
#
providers:
  # configure only from environment
  # https://github.com/hashicorp/vault/blob/api/v1.0.4/api/client.go#L28
  # this vars should not go through to the executing cmd
  hashicorp_vault:
    env:
      FOO:
        path: cubbyhole/one
        field: hello

